[build]
  base = "."
  publish = "public/"
  command = "export CI=''NODE_ENV=production npm install && npm run-script build"
#  functions = "project/functions/" // TODO: LAMBDA FUNCTIONS

 [headers]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
