[build]
  base = "."
  publish = "public/"
  command = "npm install && npm run-script build-css && npm run-script build"
#  functions = "project/functions/" // TODO: LAMBDA FUNCTIONS

  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = true
  [build.processing.js]
    bundle = true
    minify = true
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true
    
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  
 [headers]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
